#! /usr/bin/env bash

Launchd_plist=~/Library/LaunchAgents/no.brujordet.bugger.plist

load_configuration(){
    if [[ ! -f ~/.bugger/bug.conf ]]; then
        echo "Could not find config file!"
        create_config
    fi
    . ~/.bugger/bug.conf
}

create_config(){
    echo "Generating new config to ~/.bugger/bug.conf"
    if [[ ! -d ~/.bugger ]]; then
        mkdir ~/.bugger
    fi

    cat > ~/.bugger/bug.conf << EOF
    ### Edit me, and run <bugadm reload> ###
    bugger_intervall=900
    bugger_path="$(pwd)/bin/bugger"
EOF
}

generate_job(){
    echo "Generating new Launchd job"
    cat > $Launchd_plist <<- EOF
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>Label</key>
        <string>no.brujordet.bugger</string>
        <key>ProgramArguments</key>
        <array>
            <string>$bugger_path</string>
        </array>
        <key>StandardErrorPath</key>
        <string>/dev/null</string>
        <key>StandardOutPath</key>
        <string>/dev/null</string>
        <key>StartInterval</key>
        <integer>$bugger_intervall</integer>
        <key>RunAtLoad</key>
        <true/>
    </dict>
    </plist>
EOF
}

check_bugger_status(){
    echo $(launchctl list | grep no.brujordet.bugger)
}

delete_job(){
    if [[ -f $Launchd_plist ]]; then
        echo "Deleting job"
        rm $Launchd_plist
    fi
}

start_bugger(){
    echo "Starting Bugger"
    launchctl load $Launchd_plist
}

stop_bugger(){
    if [[ ! -z "$(check_bugger_status)" ]]; then
        echo "Stopping Bugger"
        launchctl unload $Launchd_plist
    else
        echo "Bugger was not running.."
    fi
}

status_bugger(){
    running=$(launchctl list | grep no.brujordet.bugger)
    if [[ ! -z "$(check_bugger_status)" ]]; then
        echo "Bugger is running!"
    else
        echo "Bugger is not running.."
    fi
}




############################

case $1 in
    install)
        load_configuration
        generate_job
    ;;
    reload)
        stop_bugger
        delete_job
        load_configuration
        generate_job
        start_bugger
    ;;
    status)
        status_bugger
    ;;
    start)
        start_bugger
    ;;
    stop)
        stop_bugger
    ;;
    cleanup)
        stop_bugger
        delete_job
    ;;
    *)
        echo "usage: $0 (install|start|stop|reload|cleanup)"
    ;;
esac